modLoader = "javafml"
loaderVersion = "[4,)"
license = "$project.license"

[[mods]] #mandatory
modId = "$project.mod.id"
version = "$version"
displayName = "$name"
authors = "$project.author"
logoFile = "logo-forge.png"
description = '''
$project.description
'''
updateJSONURL="https://curseupdate.com/$project.curse.id.neoforge/$project.mod.id?ml=neoforge" #optional
[[dependencies.$project.mod.id]]
modId = "neoforge" #mandatory
required = true #mandatory
versionRange = "$dependencies.net.neoforged.neoforge.maven"
ordering = "AFTER"
side = "BOTH"
[[dependencies.$project.mod.id]]
modId = "minecraft" #mandatory
required = true #mandatory
versionRange = "${minecraft.range.neoforge.get()}"
ordering = "AFTER"
side = "BOTH"
[[dependencies.$project.mod.id]]
modId = "scena" #mandatory
required = true #mandatory
versionRange = "$dependencies.com.communi_suggestu.scena.neoforge.maven"
ordering = "AFTER"
side = "BOTH"
